---
- hosts: network
  gather_facts: no
  connection: local
  tasks:
    - name: show version
      ios_command:
        commands:
          - show version
      register: results

    - debug: var=results
