---
- name: Configure DNS resolver information
  junos_system:
    domain_search: "{{ network_domain_search | default(omit) }}"
    lookup_source: "{{ network_lookup_source | default(omit) }}"
    lookup_enabled: "{{ network_lookup_enabled | default(omit) }}"
    name_servers: "{{ network_name_servers | default(omit) }}"
  connection: netconf
