---
- name: Show F5 facts
  hosts: tmos
  connection: local
  gather_facts: False

  tasks:

    - name: Get BIG-IP facts
      bigip_facts:
        server: "{{ ansible_host }}"
        user: "{{ network_username | default(omit) }}"
        password: "{{ network_password | default(omit) }}"
        validate_certs: no
        include: "system_info,software,self_ip"
      register: bigip_facts

    - debug: var=bigip_facts
