---
- name: Configure the F5s
  hosts: tmos
  connection: local
  gather_facts: False

  vars:
    network_username: admin
    network_password: netsuperadmin
    interfaces:
      - ip: 10.1.1.1/24
      - ip: 10.1.2.1/24

  tasks:

    - name: Set timezone
      bigip_device_ntp:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        timezone: "America/New_York"
        validate_certs: "no"

    - name: Create Outside VLAN
      bigip_vlan:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        name: "outside"
        untagged_interfaces: 1.1
        validate_certs: "no"

    - name: Address Outside Interface
      bigip_selfip:
          address: "{{ interfaces[0].ip | ipaddr('address') }}"
          name: "outside"
          netmask: "{{ interfaces[0].ip | ipaddr('netmask') }}"
          server: "{{ ansible_host }}"
          user: "{{ network_username }}"
          password: "{{ network_password }}"
          validate_certs: "no"
          vlan: "outside"

    - name: Create Inside VLAN
      bigip_vlan:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        name: "inside"
        untagged_interfaces: 1.2
        validate_certs: "no"

    - name: Address Inside Interface
      bigip_selfip:
          address: "{{ interfaces[1].ip | ipaddr('address') }}"
          name: "inside"
          netmask: "{{ interfaces[1].ip | ipaddr('netmask') }}"
          server: "{{ ansible_host }}"
          user: "{{ network_username }}"
          password: "{{ network_password }}"
          validate_certs: "no"
          vlan: "inside"
