---
- name: Configure the F5s
  hosts: tmos
  connection: local
  gather_facts: False

  vars:
    network_username: admin
    network_password: netsuperadmin
    interfaces:
      - { name: outside, interface: 1.1, ip: 10.1.1.254/24 }
      - { name: inside, interface: 1.2, ip: 10.1.2.254/24 }

  tasks:

    - name: Set timezone
      bigip_device_ntp:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        timezone: "America/New_York"
        validate_certs: "no"

    - name: Ensure state of VLAN interface
      bigip_vlan:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        name: "{{ bigip_vlan.name }}"
        untagged_interfaces: "{{ bigip_vlan.interface }}"
        validate_certs: "no"
      with_items: "{{ interfaces | default([]) }}"
      loop_control:
        loop_var: bigip_vlan

    - name: Ensure selfip address on interface
      bigip_selfip:
          address: "{{ bigip_selfip.ip | ipaddr('address') }}"
          name: "outside"
          netmask: "{{ bigip_selfip.ip | ipaddr('netmask') }}"
          server: "{{ ansible_host }}"
          user: "{{ network_username }}"
          password: "{{ network_password }}"
          validate_certs: "no"
          vlan: "{{ bigip_selfip.name }}"
      with_items: "{{ interfaces | default([]) }}"
      loop_control:
        loop_var: bigip_selfip
