---
- name: Configure the F5s hosts
  hosts: f5:&hosts
  gather_facts: False

  tasks:
    - name: Ensure state of httpd
      yum:
        name: httpd
        state: present

    - name: Ensure state of service
      service:
        name: httpd
        state: started
