---
- hosts: network
  connection: network_cli
  gather_facts: no
  vars:
    minimum_version_list:
      ios: 16.06.01
      junos: 17.2R1.13

  tasks:
    - include_role:
        name: network_version
