---
- name: Setup BGP on the Hub
  hosts: hub_routers
  gather_facts: no
  tasks:
    - include_role:
        name: network_bgp_peer
      vars:
        bgp_router_id: "{{ tunnel_network | ipaddr(1) | ipaddr('address') }}"
        bgp_neighbor_ip: "{{ hostvars[item].tunnel_ip | ipaddr('address') }}"
        bgp_neighbor_asn: "{{ tunnel_asn + hostvars[item].site_number|int }}"
        bgp_asn: "{{ tunnel_asn }}"
        bgp_local_network: "{{ interfaces.2.ip | ipaddr('network') }}"
      with_items: "{{ groups.spoke_routers | default([]) }}"

- name: Setup BGP on the Spoke
  hosts: spoke_routers
  gather_facts: no
  tasks:
    - include_role:
        name: network_bgp_peer
      vars:
        bgp_router_id: "{{ tunnel_ip | ipaddr('address') }}"
        bgp_neighbor_ip: "{{ tunnel_network | ipaddr(1) | ipaddr('address') }}"
        bgp_neighbor_asn: "{{ tunnel_asn }}"
        bgp_asn: "{{ tunnel_asn + site_number|int }}"
        bgp_local_network: "{{ interfaces.2.ip | ipaddr('network') }}"
